backend:
    name: github
    branch: main
    repo: cyscale/cyscale.com
    commit_messages:
        create: 'Create {{collection}} “{{slug}}”'
        update: 'Update {{collection}} “{{slug}}”'
        delete: 'Delete {{collection}} “{{slug}}”'
        uploadMedia: '[skip ci] Upload “{{path}}”'
        deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow
collections:
    - name: 'blog'
      label: 'Blog'
      folder: 'src/markdown/blog'
      create: true
      slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
      fields:
          - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'blog-post' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'SEO Title', name: 'seoTitle', widget: 'string' }
          - {
                label: 'Author',
                name: 'authors',
                widget: 'select',
                options: ['Sabrina Lupșan', 'Andrei Ștefănie', 'Manuela Țicudean', 'Ovidiu Cical']
            }
          - { label: 'Permalink', name: 'permalink', widget: 'string' }
          - {
                label: 'Categories',
                name: 'categories',
                widget: 'select',
                multiple: true,
                min: 1,
                max: 3,
                default: ['News'],
                options:
                    [
                        'News',
                        'Product',
                        'CSPM',
                        'Compliance',
                        'CNAPP',
                        'Engineering',
                        'IAM',
                        'Misconfigurations',
                        'Cloud Security',
                        'Encryption',
                        "Cloud Native Security"
                    ]
            }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Description', name: 'description', widget: 'text' }
          - { label: 'SEO Description', name: 'seoDescription', widget: 'string' }
          - { label: 'Featured Post', name: 'featuredpost', widget: 'boolean' }
          - { label: 'Featured Image', name: 'featuredimage', widget: image }
          - {
                label: 'Table of Contents',
                name: 'tableOfContents',
                widget: 'boolean',
                default: false,
                required: false,
                hint: 'Consult TOC documentation for an effective Table of Content: https://cyscale.atlassian.net/wiki/spaces/WEB/pages/1115881473/Table+of+contents+documentation'
            }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - { label: 'Tags', name: 'tags', widget: 'list' }
    - name: 'category'
      label: 'Category'
      folder: 'src/markdown/categories'
      create: true
      slug: '{{fields.slug}}'
      editor:
          preview: false
      fields:
          - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'category' }
          - { label: 'SEO Title', name: 'seoTitle', widget: 'string' }
          - { label: 'Slug', name: 'slug', widget: 'string' }
          - { label: 'Name', name: 'name', widget: 'string' }
          - { label: 'SEO Description', name: 'seoDescription', widget: 'string' }
          - { label: 'Disabled', name: 'disabled', widget: 'boolean', default: false }
    - name: 'career'
      label: 'Careers'
      folder: 'src/markdown/careers'
      create: true
      slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
      fields:
          - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'career-page' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'SEO Title', name: 'seoTitle', widget: 'string' }
          - { label: 'Disabled', name: 'disabled', widget: 'boolean', default: false }
          - { label: 'Location', name: 'location', widget: 'string', default: 'Remote' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Permalink', name: 'permalink', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'text' }
          - { label: 'SEO Description', name: 'seoDescription', widget: 'text' }
          - { label: 'Skills', name: 'skills', widget: 'text' }
          - {
                label: 'Experience',
                name: 'experience',
                widget: 'select',
                options: ['intern', 'junior', 'junior/mid', 'mid', 'mid/senior', 'senior', ''],
                default: 'mid/senior'
            }
          - {
                label: 'Department',
                name: 'department',
                widget: 'select',
                options:
                    [
                        'Sales',
                        'Product',
                        'Marketing',
                        'Management',
                        'Engineering',
                        'Customer Success',
                        'HR & Recruiting',
                        ''
                    ],
                default: 'mid/senior'
            }
          - { label: 'Work Type', name: 'workType', widget: 'select', options: ['hybrid', 'remote', 'in-office', ''] }
          - {
                label: 'Employment Type',
                name: 'employmentType',
                widget: 'select',
                options: ['full-time', 'part-time', 'contract', ''],
                default: 'hybrid'
            }
          - { label: 'Body', name: 'body', widget: 'markdown' }
    - name: 'pages'
      label: 'Pages'
      folder: 'src/markdown/pages'
      create: true
      slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
      fields:
          - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'pages' }
          - {
                label: 'Page Name',
                name: 'pageName',
                widget: 'string',
                hint: 'Should not contain any spaces, ex: SKGPage for SecurityKnowledge Graph'
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'string' }
          - { label: 'Category Path', name: 'categoryPath', widget: 'select', options: ['use-cases', 'products'] }
          - { label: 'Path', name: 'path', widget: 'string', hint: 'Should not contain any spaces' }
          - {
                label: 'Sections',
                name: 'sections',
                widget: 'select',
                options:
                    [
                        'hero',
                        'textImageRow',
                        'secondTextImageRow',
                        'alignTeamsSection',
                        'featuresSection',
                        'cloudComplianceSection',
                        'ctaSection'
                    ],
                default: ['hero'],
                multiple: true
            }
          - label: 'Hero'
            name: 'hero'
            widget: 'object'
            fields:
                - { label: 'Hero Background', name: 'heroBackground', widget: image, required: false }
                - { label: 'Hero Image', name: 'heroImage', widget: image }
                - { label: 'Hero Image Alt', name: 'heroImageAlt', widget: 'string' }
                - {
                      label: 'Hero Title',
                      name: 'heroTitle',
                      widget: 'markdown',
                      hint: 'For title use H1 Hero and nothing more'
                  }
                - {
                      label: 'Custom Components',
                      name: 'customComponents',
                      widget: 'boolean',
                      default: false,
                      hint: 'For using Netlify custom components in the markdown or Rich Text'
                  }
                - { label: 'Hero Markdown', name: 'heroMarkdown', widget: 'markdown' }
          - label: 'Text Image Row'
            name: 'textImageRow'
            widget: 'list'
            allow_add: true
            fields:
                - {
                      label: 'Row Start Grid Cols',
                      name: 'rowStartGridCols',
                      widget: 'select',
                      options: ['5', '6', '7'],
                      multiple: false,
                      default: ['6']
                  }
                - {
                      label: 'Row End Grid Cols',
                      name: 'rowEndGridCols',
                      widget: 'select',
                      options: ['5', '6', '7'],
                      multiple: false,
                      default: ['6']
                  }
                - {
                      label: 'Row Image Position',
                      name: 'rowImagePosition',
                      widget: 'select',
                      options: ['left', 'right'],
                      multiple: false
                  }
                - { label: 'Row Image', name: 'rowImage', widget: image, required: false }
                - { label: 'Row Alt', name: 'rowAlt', widget: 'string', required: false }
                - {
                      label: 'Row Subtitle',
                      name: 'rowSubtitle',
                      widget: 'markdown',
                      required: false,
                      hint: 'For subtitle use just H2 Subtitle and nothing more'
                  }
                - {
                      label: 'Custom Components',
                      name: 'customComponents',
                      widget: 'boolean',
                      default: false,
                      required: false,
                      hint: 'For using Netlify custom components in the markdown or Rich Text'
                  }
                - { label: 'Row Markdown', name: 'rowMarkdown', widget: 'markdown', required: false }
                - {
                      label: 'Row Background',
                      name: 'rowBackground',
                      widget: 'select',
                      options: ['#FFFFFF', '#F3F8FF'],
                      multiple: false
                  }
          - label: 'Second Text Image Row'
            name: 'secondTextImageRow'
            widget: 'list'
            allow_add: true
            fields:
                - {
                      label: 'Row Start Grid Cols',
                      name: 'rowStartGridCols',
                      widget: 'select',
                      options: ['5', '6', '7'],
                      multiple: false,
                      default: ['6']
                  }
                - {
                      label: 'Row End Grid Cols',
                      name: 'rowEndGridCols',
                      widget: 'select',
                      options: ['5', '6', '7'],
                      multiple: false,
                      default: ['6']
                  }
                - {
                      label: 'Row Image Position',
                      name: 'rowImagePosition',
                      widget: 'select',
                      options: ['left', 'right'],
                      multiple: false
                  }
                - { label: 'Row Image', name: 'rowImage', widget: image, required: false }
                - { label: 'Row Alt', name: 'rowAlt', widget: 'string', required: false }
                - {
                      label: 'Row Subtitle',
                      name: 'rowSubtitle',
                      widget: 'markdown',
                      required: false,
                      hint: 'For subtitle use just H2 Subtitle and nothing more'
                  }
                - {
                      label: 'Custom Components',
                      name: 'customComponents',
                      widget: 'boolean',
                      default: false,
                      required: false,
                      hint: 'For using Netlify custom components in the markdown or Rich Text'
                  }
                - { label: 'Row Markdown', name: 'rowMarkdown', widget: 'markdown', required: false }
                - {
                      label: 'Row Background',
                      name: 'rowBackground',
                      widget: 'select',
                      options: ['#FFFFFF', '#F3F8FF'],
                      multiple: false
                  }
          - label: 'Features'
            name: 'featuresSection'
            widget: 'list'
            allow_add: true
            fields:
                - { label: 'Feature Title', name: 'featureTitle', widget: 'string', required: false }
                - { label: 'Feature Text', name: 'featureText', widget: 'string', required: false }
          - label: 'CTA'
            name: 'ctaSection'
            widget: 'object'
            fields:
                - {
                      label: 'CTA Markdown',
                      name: 'ctaMarkdown',
                      widget: 'markdown',
                      required: false,
                      hint: 'Use H1 CTA and nothing more'
                  }
